= Stuck in the 70's?: Sanitize shell script from the disco era

This presentation is diving into bash features I do not usually encounter in the
wild. As a matter of fact most shell scripts are written without taking advantage
of the features introduced by Korn Shell in the early 80's and the Bash Shell
later in the same decade.

With Bash being ubiquitous throughout the Unix world there is little reason not to
take advantage of the more advanced features it provides. During the presentation
one learns how to make Bash scripts more predictable, less prone to errors an speed
up the execution time by using built in functions.

== Repo clone

This repository contains submodules for the asciidocotor sytles. To properly
clone the repository use the following command:

[source,console]
----
git clone --recursive https://github.com/uroesch/Stuck-in-the-70s.git
----

== Build documents

This presentation is based on asciidoctor sources and needs to be built or
converted to the 3 supported formats. Currently these are:
* Presentation (reveal.js)
* HTML document
* PDF document

=== Presentation

The reveal.js is presentation is stored under the `SLIDES` directory.

[source,console]
----
rake revealjs
----

=== HTML

The self-contained HTML document can be found under the `HTML` directory.
There may be several subdirectories depending on the style sheet used.

[source,console]
----
rake html
----

=== PDF

The PDF document can be found under the `PDF` directory.
There may be several subdirectories depending on the style sheet used.

[source,console]
----
rake pdf
----
