= Matrix
:icons: font

[cols="80%,10*", options="header"]
|===
| Feature / Version
^| 3.0
^| 3.1
^| 3.2
^| 4.0
^| 4.1
^| 4.2
^| 4.3
^| 4.4
^| 5.0
^| 5.1

h| `declare -a` (Array)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -A` (Hash)
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -f` (Function)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -g` (Global)
|
|
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -i` (Integer)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -l` (Lowercase)
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -r` (Readonly)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -u` (Uppercase)
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| `declare -x` (Export)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Operator `+=` (Append)
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Operator `=~` (Regex)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Parameter expansion `${foo,}` (Lowercase)
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Parameter expansion `${foo^}` (Uppercase)
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Parameter expansion `${!f*}` (Partial)
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Redirect `&>`
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Redirect `\|&`
|
|
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

h| Variable assignment `printf -v`
|
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]
^| icon:check-square[]

|===
